### ISSUE TITLE
unable to add package in unity project using git url

### ISSUE THREAD

**Issue by Ashish-Ranjan** [mobiledgex/edge-multiplay-unity-client#31]
[Package Manager Window] Unable to add package [https://github.com/mobiledgex/edge-multiplay-unity-client.git]:
  [https://github.com/mobiledgex/edge-multiplay-unity-client.git] does not point to a valid package. No package manifest was found.
UnityEditor.EditorApplication:Internal_CallUpdateFunctions ()

**Comment by ah1053** [comment]
Hi Ashish You can download EdgeMultiplay as a unity package from the Releases page https://github.com/mobiledgex/edge-multiplay-node-server/releases/
The repository is not configured to be imported as PackageManager(Unity Package)

**Comment by Ashish-Ranjan** [comment]
Thank you, really apricate your help.
